name: Create Release for tag1

on:
  push:
    tags:
      - 'tag1'
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: tag1
          release_name: Release with Tag 1
          body: |
            This release is created using tag1.
          draft: false
          prerelease: false
